version: "3.8"
services:
  myapp-dev:
    image: nginx:latest
    container_name: myapp-dev
    ports:
      - "8080:80"
    volumes:
      - ./dev:/usr/share/nginx/html
    networks:
      - myapp-net

  myapp-prod:
    image: nginx:latest
    container_name: myapp-prod
    ports:
      - "80:80"
    volumes:
      - ./production:/usr/share/nginx/html
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: bridge
 